### PR TITLE
Added types.

### PR DESCRIPTION
**Pull request by teymour-aldridge**
Adding custom types is likely to make the program more easily extendable and maintainable.

### CODE REVIEW

**Comment by dmoa** [comment]
Runs the same when you comment out your added code. Can you elaborate on your ideas of making it more maintainable?

**Comment by dmoa** [comment]
Do you mean e.g. using the image class instead of passing the path to the image in UserFile.py?

**Comment by teymour-aldridge** [comment]
Yes. I think seperating everything out like this will make it easier to modifiy specific parts of the application.

**Comment by dmoa** [comment]
I'll see if I can work on it.

**Pull request merged**
